const rawDays=[
{date:'2026-06-20',label:'20. 6.',revenue:1080.01,netSales:934.05,orders:10,aov:93.405,spend:221.41,metaRoas:1.38,ctr:1.57,cpm:5.21,clicks:669,impressions:42521,metaPurchases:4,cr:1.4675052410901468,sessions:477,bei:68},
{date:'2026-06-21',label:'21. 6.',revenue:202.82,netSales:159.38,orders:6,aov:52.673,spend:272.69,metaRoas:.68,ctr:1.74,cpm:5.08,clicks:935,impressions:53633,metaPurchases:3,cr:.8849557522123894,sessions:565,bei:21},
{date:'2026-06-22',label:'22. 6.',revenue:761.06,netSales:625.52,orders:9,aov:69.502,spend:232.13,metaRoas:1.14,ctr:1.66,cpm:5.54,clicks:697,impressions:41893,metaPurchases:6,cr:1.1131725417439702,sessions:539,bei:53},
{date:'2026-06-23',label:'23. 6.',revenue:1098.65,netSales:885.67,orders:14,aov:63.262,spend:214.04,metaRoas:5.05,ctr:1.66,cpm:4.69,clicks:755,impressions:45615,metaPurchases:12,cr:1.2939001848428837,sessions:541,bei:87},
{date:'2026-06-24',label:'24. 6.',revenue:182.36,netSales:153.25,orders:2,aov:76.625,spend:211.13,metaRoas:.28,ctr:1.39,cpm:3.86,clicks:762,impressions:54676,metaPurchases:1,cr:.19723865877712032,sessions:507,bei:17},
{date:'2026-06-25',label:'25. 6.',revenue:935.18,netSales:796.91,orders:12,aov:68.512,spend:211.53,metaRoas:1.36,ctr:1.56,cpm:4.06,clicks:816,impressions:52148,metaPurchases:4,cr:1.4678899082568808,sessions:545,bei:61},
{date:'2026-06-26',label:'26. 6.',revenue:213.36,netSales:176.68,orders:2,aov:88.34,spend:66.25,metaRoas:2.17,ctr:1.34,cpm:3.96,clicks:224,impressions:16732,metaPurchases:1,cr:0,sessions:156,bei:41,partial:true}
];
const campaigns=[
{name:'[DE] - DABA - A+',spend:771.98,roas:.68,ctr:1.51,cpm:6.97},
{name:'[T2] - DABA - A+',spend:209.98,roas:1.95,ctr:1.53,cpm:2.60},
{name:'[T2] - VIDEO - A+ - ai v1',spend:170.94,roas:4.69,ctr:1.59,cpm:2.33},
{name:'[DE] - VIDEO - A+ - ai v1',spend:133.79,roas:.90,ctr:1.83,cpm:9.77},
{name:'[DE] - VIDEO - A+ - perf',spend:56.69,roas:1.77,ctr:1.41,cpm:6.68},
{name:'[DE] - VIDEO - A+ - organic',spend:52.40,roas:null,ctr:2.13,cpm:6.20},
{name:'[IT] - DABA - A+ - RMK',spend:33.11,roas:9.01,ctr:2.02,cpm:2.85}
];
const products=[
{name:'TORNZ - Baggy Denim Embroidered Jorts',gross:441.83,net:238.25,orders:8},
{name:'WINGLY - Baggy Cotton Graphic Shorts',gross:292.66,net:175.60,orders:5},
{name:'STRIPASO - Baggy Graphic Jeans',gross:230.47,net:130.49,orders:3},
{name:'SYMBOLIKA - Oversized Print Zip Up Hoodie',gross:200.50,net:111.15,orders:2},
{name:'VERTEBRAX - Boxy Fit Print T-shirt',gross:172.37,net:68.77,orders:4},
{name:'WESTY - Oversized Graphic Shirt',gross:156.18,net:88.51,orders:2},
{name:'WINGY - Graphic Polo Shirt',gross:140.21,net:88.34,orders:3},
{name:'FREAKING - Oversized Print T-shirt',gross:134.49,net:50.52,orders:3},
{name:'SPIKY - Oversized Print T-Shirt',gross:128.68,net:80.71,orders:3},
{name:'SKICEN - Oversized Graphic Jersey T-Shirt',gross:127.03,net:76.23,orders:3}
];

const eur=new Intl.NumberFormat('sk-SK',{style:'currency',currency:'EUR',maximumFractionDigits:2});
const num=new Intl.NumberFormat('sk-SK',{maximumFractionDigits:2});
const pct=v=>v==null||Number.isNaN(v)?'—':num.format(v)+' %';
const money=v=>v==null||Number.isNaN(v)?'—':eur.format(v);
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
let selectedMetric='revenue',mainChart,efficiencyChart,campaignChart;
const rangeEls={from:document.getElementById('fromDate'),to:document.getElementById('toDate')};
const beiEls={from:document.getElementById('beiFrom'),to:document.getElementById('beiTo')};
const gpEls={from:document.getElementById('gpFrom'),to:document.getElementById('gpTo')};
const rows=()=>rawDays.filter(r=>r.date>=rangeEls.from.value&&r.date<=rangeEls.to.value);
const beiRows=()=>rawDays.filter(r=>r.date>=beiEls.from.value&&r.date<=beiEls.to.value);
const gpRows=()=>rawDays.filter(r=>r.date>=gpEls.from.value&&r.date<=gpEls.to.value);

function calculateBei(a){if(!a.revenue||!a.metaPurchases||!a.spend||a.metaRoas==null)return null;const pno=a.spend/a.revenue*100,blended=a.revenue/a.spend,cpa=a.spend/a.metaPurchases,gp=(a.netSales/a.orders)*.35,gpc=gp/cpa*100,adEff=(a.metaRoas/3.7210763859043348*50)+(22.281203830369353/cpa*30)+(a.ctr/2.553477572363772*20),siteEff=(a.cr/1.0392857361709429*70)+((a.netSales/a.orders)/78.84036556603775*30);return Math.round((blended/8.209532919602445*30)+(12.180960960790275/pno*25)+(gpc/100*15)+(adEff/100*15)+(siteEff/100*15))}
function aggregate(list){const sum=k=>list.reduce((a,r)=>a+(r[k]||0),0),revenue=sum('revenue'),netSales=sum('netSales'),spend=sum('spend'),orders=sum('orders'),clicks=sum('clicks'),impressions=sum('impressions'),metaPurchases=sum('metaPurchases'),sessions=sum('sessions'),metaRevenue=list.reduce((a,r)=>a+(r.metaRoas==null?0:r.spend*r.metaRoas),0),metaSpend=list.reduce((a,r)=>a+(r.metaRoas==null?0:r.spend),0);const cr=sessions?list.reduce((a,r)=>a+(r.cr||0)*r.sessions,0)/sessions:0,ctr=impressions?clicks/impressions*100:0;const agg={revenue,netSales,spend,orders,clicks,impressions,metaPurchases,sessions,aov:orders?netSales/orders:null,pno:revenue?spend/revenue*100:null,blendedRoas:spend&&revenue?revenue/spend:null,metaRoas:metaSpend?metaRevenue/metaSpend:null,ctr,cpm:impressions?spend/impressions*1000:null,cpa:metaPurchases?spend/metaPurchases:null,cr};agg.bei=calculateBei(agg);return agg}
function kpiStatus(k,v){if(v==null)return'warn';if(k==='metaRoas')return v>=3.5?(v>=4?'pos':'warn'):'neg';if(k==='blendedRoas')return v>=6.7?(v>=7.5?'pos':'warn'):'neg';if(k==='pno')return v<=15?(v<=13.5?'pos':'warn'):'neg';if(k==='cpa')return v<=26?(v<=24?'pos':'warn'):'neg';if(k==='ctr')return v>=1.8?(v>=2.2?'pos':'warn'):'neg';if(k==='cpm')return'warn';if(k==='bei')return v>=100?'pos':v>=80?'warn':'neg';return'warn'}
function statusText(k,v){const s=kpiStatus(k,v);if(v==null)return'bez dát';if(k==='cpm')return'sledovať podľa krajiny';if(s==='pos')return'ideálny stav';if(s==='warn')return'v poriadku';return'slabší výsledok'}

const GP=[
 {k:'metaRoas',label:'Meta ROAS',fmt:'num',min:0,max:6,lo:4.0,hi:4.5,goal:'4,0-4,5',limit:'min 3,5+ · scale ~5,0+'},
 {k:'blendedRoas',label:'Blended ROAS',fmt:'num',min:0,max:11,lo:7.5,hi:8.5,goal:'7,5-8,5',limit:'min 6,7+ · <5,5 slabšie'},
 {k:'pno',label:'PNO / Marketing',fmt:'pct',min:0,max:40,lo:12,hi:13.5,goal:'12-13,5 %',limit:'stabilne ~15 %, >18 % riziko'},
 {k:'cpa',label:'CPA',fmt:'eur',min:0,max:50,lo:20,hi:24,goal:'20-24 €',limit:'max ~26 €, >30 € slabšie'},
 {k:'ctr',label:'CTR Meta',fmt:'pct',min:0,max:4,lo:2.2,hi:2.8,goal:'2,2-2,8 %',limit:'min ~1,8 %, <1,5 % slabšie'},
 {k:'cpm',label:'CPM',fmt:'eur',flat:true,limit:'podľa krajiny · vysoké CPM + slabý ROAS je negatívny signál'},
 {k:'bei',label:'Business Efficiency Index',fmt:'num',min:0,max:140,lo:100,hi:140,goal:'100+',limit:'pod 80 slabší scale stav'}
];
function fmtVal(f,v){if(v==null)return'—';if(f==='eur')return eur.format(v);if(f==='pct')return num.format(v)+'<span class="u">%</span>';return num.format(v)}
function renderGuards(){const list=gpRows();if(!list.length)return;const a=aggregate(list);const pos=(c,v)=>clamp((v-c.min)/(c.max-c.min)*100,1.5,98.5);document.getElementById('gauges').innerHTML=GP.map(c=>{const v=a[c.k],s=kpiStatus(c.k,v);if(c.flat){return `<article class="gp gp-flat"><div class="gp-top"><div class="gp-label">${c.label}</div><span class="tag warn">sledovať</span></div><div class="gp-val">${fmtVal(c.fmt,v)}</div><div class="gauge-flat"></div><div class="gp-goals"><div class="gp-goal"><span>Pásmo</span><b>${c.limit}</b></div></div></article>`}const zl=pos(c,c.lo),zr=pos(c,c.hi),mk=pos(c,v);return `<article class="gp ${s==='neg'?'is-neg':''}"><div class="gp-top"><div class="gp-label">${c.label}</div><span class="tag ${s}">${statusText(c.k,v)}</span></div><div class="gp-val">${fmtVal(c.fmt,v)}</div><div class="gauge"><div class="gauge-track"><div class="gauge-zone" style="left:${zl}%;width:${Math.max(zr-zl,1.5)}%"></div><div class="gauge-marker ${s}" style="left:${mk}%"></div></div><div class="gauge-scale"><span>${num.format(c.min)}</span><span>${num.format(c.max)}</span></div></div><div class="gp-goals"><div class="gp-goal"><span>Cieľ</span><b>${c.goal}</b></div><div class="gp-goal"><span>Hranica</span><b>${c.limit}</b></div></div></article>`}).join('')}

function renderToday(){const t=rawDays.find(r=>r.partial)||rawDays[rawDays.length-1],pno=t.spend/t.revenue*100,blended=t.revenue/t.spend,cpa=t.metaPurchases?t.spend/t.metaPurchases:null;const cells=[{l:'Tržby',v:money(t.revenue),s:null},{l:'Ad spend',v:money(t.spend),s:['warn','priebežné']},{l:'PNO',v:pct(pno),s:[kpiStatus('pno',pno),statusText('pno',pno)]},{l:'Blended ROAS',v:num.format(blended),s:[kpiStatus('blendedRoas',blended),statusText('blendedRoas',blended)]},{l:'Meta ROAS',v:num.format(t.metaRoas),s:[kpiStatus('metaRoas',t.metaRoas),statusText('metaRoas',t.metaRoas)]},{l:'CPA',v:money(cpa),s:[kpiStatus('cpa',cpa),statusText('cpa',cpa)]},{l:'CR',v:pct(t.cr),s:[t.cr>=1?'pos':t.cr>=.5?'warn':'neg',t.cr>=1?'silné':t.cr>=.5?'v poriadku':'slabší výsledok']},{l:'BEI',v:num.format(t.bei),s:[kpiStatus('bei',t.bei),statusText('bei',t.bei)]},{l:'AOV',v:money(t.aov),s:null},{l:'Objednávky',v:num.format(t.orders),s:null}];document.getElementById('todayGrid').innerHTML=cells.map(c=>`<div class="kpi"><div class="kpi-l">${c.l}</div><div class="kpi-v">${c.v}</div><div class="kpi-foot">${c.s?`<span class="tag ${c.s[0]}">${c.s[1]}</span>`:''}</div></div>`).join('')}

const vGrad=(ctx,from,to)=>{const ch=ctx.chart,{ctx:c,chartArea}=ch;if(!chartArea)return from;const g=c.createLinearGradient(0,chartArea.top,0,chartArea.bottom);g.addColorStop(0,from);g.addColorStop(1,to);return g};
const hGrad=(ctx,from,to)=>{const ch=ctx.chart,{ctx:c,chartArea}=ch;if(!chartArea)return from;const g=c.createLinearGradient(chartArea.left,0,chartArea.right,0);g.addColorStop(0,from);g.addColorStop(1,to);return g};
const beiBands={id:'beiBands',beforeDraw(chart){if(chart.canvas.id!=='efficiencyChart')return;const{ctx,chartArea,scales}=chart;if(!chartArea||!scales.y)return;const zones=[{from:100,to:140,color:'rgba(21,128,61,.06)'},{from:80,to:100,color:'rgba(180,83,9,.07)'},{from:0,to:80,color:'rgba(220,38,38,.055)'}];ctx.save();zones.forEach(z=>{const y1=scales.y.getPixelForValue(z.to),y2=scales.y.getPixelForValue(z.from);ctx.fillStyle=z.color;ctx.fillRect(chartArea.left,Math.max(chartArea.top,y1),chartArea.right-chartArea.left,Math.min(chartArea.bottom,y2)-Math.max(chartArea.top,y1));});ctx.restore();}};
function baseOptions(){return{responsive:true,maintainAspectRatio:false,layout:{padding:{top:6}},animation:{duration:650,easing:'easeOutQuart'},interaction:{mode:'index',intersect:false},plugins:{legend:{labels:{color:'#3f3f46',boxWidth:8,boxHeight:8,usePointStyle:true,pointStyle:'circle',padding:15,font:{family:'Inter',size:12,weight:'500'}}},tooltip:{backgroundColor:'#09090b',titleColor:'#fff',bodyColor:'#d4d4d8',borderColor:'rgba(255,255,255,.08)',borderWidth:1,padding:12,cornerRadius:10,boxPadding:5,usePointStyle:true,titleFont:{family:'JetBrains Mono',weight:'600',size:12},bodyFont:{family:'Inter',size:12}}},scales:{x:{ticks:{color:'#a1a1aa',padding:8,font:{family:'JetBrains Mono',size:10.5}},grid:{display:false},border:{display:false}},y:{ticks:{color:'#a1a1aa',padding:10,maxTicksLimit:6,font:{family:'JetBrains Mono',size:10.5}},grid:{color:'rgba(9,9,11,.05)',drawTicks:false},border:{display:false}}}}}
function renderCharts(list){const labels=list.map(r=>r.label);if(mainChart)mainChart.destroy();const ds=selectedMetric==='revenue'?[{type:'bar',label:'Tržby',data:list.map(r=>r.revenue),backgroundColor:c=>vGrad(c,'#18181b','#52525b'),borderWidth:0,borderRadius:7,borderSkipped:false,maxBarThickness:26,order:2},{type:'line',label:'Spend',data:list.map(r=>r.spend),borderColor:'#dc2626',backgroundColor:c=>vGrad(c,'rgba(220,38,38,.15)','rgba(220,38,38,0)'),tension:.4,cubicInterpolationMode:'monotone',pointRadius:0,pointHoverRadius:5,pointHoverBackgroundColor:'#dc2626',pointHoverBorderColor:'#fff',pointHoverBorderWidth:2,borderWidth:2.5,fill:true,order:1}]:[{type:'line',label:selectedMetric==='pno'?'PNO %':selectedMetric==='spend'?'Spend':'Blended ROAS',data:list.map(r=>selectedMetric==='pno'?(r.revenue?r.spend/r.revenue*100:null):selectedMetric==='spend'?r.spend:r.revenue/r.spend),borderColor:'#09090b',backgroundColor:c=>vGrad(c,'rgba(9,9,11,.12)','rgba(9,9,11,0)'),tension:.4,cubicInterpolationMode:'monotone',pointRadius:0,pointHoverRadius:5,pointHoverBackgroundColor:'#09090b',pointHoverBorderColor:'#fff',pointHoverBorderWidth:2,borderWidth:2.5,fill:true}];document.getElementById('mainChartTitle').textContent=selectedMetric==='revenue'?'Revenue vs spend':selectedMetric==='spend'?'Meta spend trend':selectedMetric==='pno'?'PNO trend':'Blended ROAS trend';mainChart=new Chart(document.getElementById('mainChart'),{data:{labels,datasets:ds},options:baseOptions()});if(campaignChart)campaignChart.destroy();campaignChart=new Chart(document.getElementById('campaignChart'),{type:'bar',data:{labels:campaigns.map(c=>c.name),datasets:[{label:'Spend',data:campaigns.map(c=>c.spend),backgroundColor:c=>hGrad(c,'#52525b','#09090b'),borderWidth:0,borderRadius:5,borderSkipped:false,maxBarThickness:15}]},options:{...baseOptions(),indexAxis:'y',scales:{x:{ticks:{color:'#a1a1aa',padding:8,font:{family:'JetBrains Mono',size:10.5}},grid:{color:'rgba(9,9,11,.05)',drawTicks:false},border:{display:false}},y:{ticks:{color:'#52525b',font:{family:'Inter',size:11}},grid:{display:false},border:{display:false}}},plugins:{legend:{display:false},tooltip:baseOptions().plugins.tooltip}}})}

function renderTables(list){document.getElementById('dailyRows').innerHTML=list.map(r=>{const pno=r.revenue?r.spend/r.revenue*100:null,blended=r.revenue/r.spend,cpa=r.metaPurchases?r.spend/r.metaPurchases:null;return `<tr><td class="lead">${r.label}${r.partial?' ·':''}</td><td class="n">${money(r.revenue)}</td><td class="n">${r.orders}</td><td class="n">${money(r.aov)}</td><td class="n">${money(r.spend)}</td><td class="n ${pno>18?'neg-c':''}">${pct(pno)}</td><td class="n ${blended<5.5?'neg-c':''}">${num.format(blended)}</td><td class="n ${r.metaRoas<3?'neg-c':''}">${num.format(r.metaRoas)}</td><td class="n ${cpa>30?'neg-c':''}">${money(cpa)}</td><td class="n ${r.ctr<1.8?'neg-c':''}">${pct(r.ctr)}</td><td class="n">${money(r.cpm)}</td><td class="n">${pct(r.cr)}</td><td class="n ${r.bei<80?'neg-c':''}">${num.format(r.bei)}</td></tr>`}).join('');document.getElementById('campaignRows').innerHTML=campaigns.map(c=>`<tr><td><span class="camp-name"><span class="dotk"></span>${c.name}</span></td><td class="n">${money(c.spend)}</td><td class="n ${c.roas!=null&&c.roas<1?'neg-c':''}">${c.roas==null?'—':num.format(c.roas)}</td><td class="n ${c.ctr<1.8?'neg-c':''}">${pct(c.ctr)}</td><td class="n">${money(c.cpm)}</td></tr>`).join('');const maxG=Math.max(...products.map(p=>p.gross));document.getElementById('productRows').innerHTML=products.map(p=>`<tr><td class="lead">${p.name}</td><td class="n prod-bar"><span style="width:${(p.gross/maxG*100).toFixed(1)}%"></span><em>${money(p.gross)}</em></td><td class="n">${money(p.net)}</td><td class="n">${p.orders}</td></tr>`).join('')}

function renderInsights(a,list){const best=[...list].sort((x,y)=>y.revenue-x.revenue)[0],worst=[...list].sort((x,y)=>(y.spend/y.revenue)-(x.spend/x.revenue))[0];document.getElementById('insights').innerHTML=[`<div class="ins neg"><i></i><div>PNO je <b>${pct(a.pno)}</b>. Stabilnejší režim je do ~15 %, takže ekonomika spendu je teraz rizikovejšia.</div></div>`,`<div class="ins neg"><i></i><div>Blended ROAS <b>${num.format(a.blendedRoas)}</b> oproti cieľu 7,5-8,5. Pod 5,5 je slabší stav na scale.</div></div>`,`<div class="ins pos"><i></i><div>Najsilnejší deň <b>${best.label}</b> - tržby <b>${money(best.revenue)}</b>, ${best.orders} obj.</div></div>`,`<div class="ins warn"><i></i><div>Najťažší PNO deň <b>${worst.label}</b> - PNO <b>${pct(worst.spend/worst.revenue*100)}</b>.</div></div>`,`<div class="ins"><i></i><div>Meta ROAS <b>${num.format(a.metaRoas)}</b> · CTR <b>${pct(a.ctr)}</b> za vybrané obdobie.</div></div>`].join('')}

function renderBei(){const list=beiRows();if(!list.length)return;const a=aggregate(list),labels=list.map(r=>r.label),beiTxt=a.bei==null?'—':num.format(a.bei);document.getElementById('beiValue').textContent=beiTxt;document.getElementById('beiFill').style.width=clamp((a.bei||0)/140*100,0,100)+'%';const bs=document.getElementById('beiStatus');bs.className='tag '+kpiStatus('bei',a.bei);bs.textContent=statusText('bei',a.bei)+' · '+beiTxt+' / 100';const dir=list.length>1?(list[list.length-1].bei-list[0].bei):0,tt=document.getElementById('beiTrendTag');tt.className='tag mono '+(dir>0?'pos':dir<0?'neg':'');tt.textContent=(dir>0?'▲ +':dir<0?'▼ ':'→ ')+Math.abs(dir)+' · '+labels[0]+'-'+labels[labels.length-1];if(efficiencyChart)efficiencyChart.destroy();efficiencyChart=new Chart(document.getElementById('efficiencyChart'),{type:'line',data:{labels,datasets:[{label:'BEI',data:list.map(r=>r.bei),borderColor:'#09090b',backgroundColor:c=>vGrad(c,'rgba(9,9,11,.13)','rgba(9,9,11,0)'),tension:.4,cubicInterpolationMode:'monotone',pointRadius:3,pointBackgroundColor:list.map(r=>r.bei>=100?'#15803d':r.bei>=80?'#b45309':'#dc2626'),pointHoverRadius:5,pointHoverBackgroundColor:'#09090b',pointHoverBorderColor:'#fff',pointHoverBorderWidth:2,borderWidth:2.5,fill:true},{label:'Cieľ 100',data:list.map(()=>100),borderColor:'rgba(21,128,61,.7)',borderDash:[5,5],pointRadius:0,borderWidth:1.5},{label:'Min 80',data:list.map(()=>80),borderColor:'rgba(180,83,9,.6)',borderDash:[3,5],pointRadius:0,borderWidth:1.5}]},options:baseOptions(),plugins:[beiBands]})}

function update(){const list=rows(),a=aggregate(list);if(!list.length)return;document.getElementById('rowCount').innerHTML=`<b>${list.length}</b> dní`;renderToday();renderCharts(list);renderTables(list);renderInsights(a,list)}
function bindPreset(attr,els,render){document.querySelectorAll(`[${attr}]`).forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll(`[${attr}]`).forEach(x=>x.classList.remove('active'));b.classList.add('active');const p=b.getAttribute(attr);if(p==='today'){els.from.value='2026-06-26';els.to.value='2026-06-26'}if(p==='3d'){els.from.value='2026-06-24';els.to.value='2026-06-26'}if(p==='7d'){els.from.value='2026-06-20';els.to.value='2026-06-26'}render()}));[els.from,els.to].forEach(i=>i.addEventListener('change',()=>{if(els.from.value>els.to.value)els.to.value=els.from.value;document.querySelectorAll(`[${attr}]`).forEach(b=>b.classList.remove('active'));render()}))}
bindPreset('data-preset',rangeEls,update);
bindPreset('data-bei',beiEls,renderBei);
bindPreset('data-gp',gpEls,renderGuards);
document.querySelectorAll('[data-metric]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-metric]').forEach(x=>x.classList.remove('active'));b.classList.add('active');selectedMetric=b.dataset.metric;renderCharts(rows())}));
update();renderBei();renderGuards();